### PR TITLE
Make dark scroll bar in dark theme

### PR DESCRIPTION
**Pull request by rakleed**

### CODE REVIEW

**Comment by rakleed** [comment]
@tvinzz @maximtop @kaprielov please take a look.

**Comment by kaprielov** [comment]
@rakleed Sorry for the late reply. You don't have to add `color-scheme` to `media`. Just add `color-scheme: light dark;` to `:root` or `html`.

**Comment by rakleed** [comment]
@kaprielov done.

**Comment by kaprielov** [comment]
I don't think `vars.pcss` is a good place to store it. `common.pcss` is better

**Comment by rakleed** [comment]
@kaprielov done.

**Comment by kaprielov** [comment]
Accept changes aa90becc55b

**Pull request closed without merging**
